name: Daily APK Update

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  update-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download APK
        run: curl -L -o downloaded.apk ${{ secrets.APK_URL }}

      - name: Calculate Hash of Downloaded APK
        id: hash_downloaded
        run: echo "DOWNLOADED_HASH=$(sha256sum downloaded.apk | awk '{print $1}')" >> $GITHUB_ENV

      - name: Check if last_apk_hash.txt exists
        id: check_hash_file
        run: |
          if [ -f last_apk_hash.txt ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Read existing hash
        if: steps.check_hash_file.outputs.exists == 'true'
        id: read_hash
        run: echo "EXISTING_HASH=$(cat last_apk_hash.txt)" >> $GITHUB_ENV

      - name: Compare hashes
        id: compare_hashes
        run: |
          if [ "${{ steps.check_hash_file.outputs.exists }}" == "true" ] && [ "${{ env.DOWNLOADED_HASH }}" == "${{ env.EXISTING_HASH }}" ]; then
            echo "same=true" >> $GITHUB_OUTPUT
          else
            echo "same=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Android SDK
        if: steps.compare_hashes.outputs.same != 'true'
        uses: android-actions/setup-android@v2

      - name: Set up Python
        if: steps.compare_hashes.outputs.same != 'true'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install fdroidserver
        if: steps.compare_hashes.outputs.same != 'true'
        run: pip install fdroidserver

      - name: Extract package name and version code
        if: steps.compare_hashes.outputs.same != 'true'
        run: |
          PACKAGE_NAME=$(aapt dump badging downloaded.apk | grep package | awk '{print $2}' | sed "s/name='//g" | sed "s/'//g")
          VERSION_CODE=$(aapt dump badging downloaded.apk | grep package | awk '{print $4}' | sed "s/versionCode='//g" | sed "s/'//g")
          VERSION_NAME=$(aapt dump badging downloaded.apk | grep package | awk '{print $3}' | sed "s/versionName='//g" | sed "s/'//g")
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Copy APK to repo directory
        if: steps.compare_hashes.outputs.same != 'true'
        run: |
          FILENAME="${PACKAGE_NAME}_${VERSION_CODE}.apk"
          mkdir -p fdroid/repo
          cp downloaded.apk "fdroid/repo/$FILENAME"

      - name: Run fdroid update
        if: steps.compare_hashes.outputs.same != 'true'
        run: |
          cd fdroid
          echo "${{ secrets.CONFIG }}" | base64 -d > config.yml
          echo "${{ secrets.KEYSTORE }}" | base64 -d > keystore.p12
          fdroid update -c

      - name: Update last_apk_hash.txt
        if: steps.compare_hashes.outputs.same != 'true'
        run: echo "${{ env.DOWNLOADED_HASH }}" > last_apk_hash.txt

      - name: Commit and push changes
        if: steps.compare_hashes.outputs.same != 'true'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add fdroid/repo/*.apk fdroid/index.* last_apk_hash.txt
          git commit -m "Update APK to version $VERSION_NAME ($VERSION_CODE)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}